services:
  api:
    build:
      context: .
      dockerfile: src/Assessment.Api/Dockerfile
    container_name: assessment-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=yamabiko.proxy.rlwy.net;Port=28713;Database=railway;Username=postgres;Password=DwhkqyOskMtwZXQclGjKcohPkIwHfVpj
    ports:
      - "5000:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: assessment-frontend
    ports:
      - "5173:80"
    depends_on:
      - api
